import NavBar from './components/NavBar';
import Footer from './components/Footer';
import { Manrope, PT_Serif } from "next/font/google";

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
  display: 'swap',
})

const pt_serif = PT_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-pt_serif',
  display: 'swap',
})


export const metadata = {
  title: "Bumjin Joo | Portfolio",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${pt_serif.variable}`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
